[package]
name = "fishing_web"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
futures = "0.3"
actix-files = "0.6"
futures-util = "0.3.30"
actix-multipart = "0.7"
sanitize-filename = "0.5"
# pyo3 = { version = "0.18", features = ["extension-module"] }