CLASH_DIR = /home/zyc/clash
CLASH_EXEC = /home/zyc/clash/clash

.PHONY: clash

RustRover:
	/opt/RustRover-2024.1.7/bin/rustrover.sh
Clion:
	/opt/clion-2024.2.0.1/bin/clion.sh
code:
	code
clash:
	cd $(CLASH_DIR) && $(CLASH_EXEC) -d .
QQ:
	~/下载/QQ_3.2.12_240819_x86_64_01.AppImage
